# Generated by Django 2.1.4 on 2018-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('COD_PART', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('NOME', models.CharField(max_length=100)),
                ('COD_PAIS', models.CharField(max_length=5)),
                ('CNPJ', models.CharField(max_length=14)),
                ('CPF', models.CharField(max_length=11)),
                ('IE', models.CharField(max_length=14)),
                ('COD_MUN', models.CharField(max_length=7)),
                ('SUFRAMA', models.CharField(max_length=9)),
                ('END', models.CharField(max_length=60)),
                ('NUM', models.CharField(max_length=10)),
                ('COMPL', models.CharField(max_length=60)),
                ('BAIRRO', models.CharField(max_length=60)),
            ],
        ),
    ]
