# Generated by Django 2.1.4 on 2018-12-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_ITEM', models.IntegerField()),
                ('COD_ITEM', models.CharField(max_length=60)),
                ('DESCR_COMPL', models.CharField(max_length=100)),
                ('QTD', models.FloatField(default=0.0)),
                ('UNID', models.CharField(max_length=6)),
                ('VL_ITEM', models.FloatField(default=0.0)),
                ('VL_DESC', models.FloatField(default=0.0)),
                ('IND_MOV', models.CharField(max_length=1)),
                ('CST_ICMS', models.CharField(max_length=3)),
                ('CFOP', models.CharField(max_length=4)),
                ('COD_NAT', models.CharField(max_length=10)),
                ('VL_BC_ICMS', models.FloatField(default=0.0)),
                ('ALIQ_ICMS', models.FloatField(default=0.0)),
                ('VL_ICMS', models.FloatField(default=0.0)),
                ('VL_BC_ICMS_ST', models.FloatField(default=0.0)),
                ('ALIQ_ST', models.FloatField(default=0.0)),
                ('VL_ICMS_ST', models.FloatField(default=0.0)),
                ('IND_APUR', models.CharField(max_length=1)),
                ('CST_IPI', models.CharField(max_length=2)),
                ('COD_ENQ', models.CharField(max_length=3)),
                ('VL_BC_IPI', models.FloatField(default=0)),
                ('ALIQ_IPI', models.FloatField(default=0)),
                ('VL_IPI', models.FloatField(default=0)),
                ('CST_PIS', models.CharField(max_length=2)),
                ('VL_BC_PIS', models.FloatField(default=0)),
                ('ALIQ_PIS', models.FloatField(default=0)),
                ('ALIQ_PIS_PERCT', models.FloatField(default=0)),
                ('QUANT_BC_PIS', models.FloatField(default=0)),
                ('VL_PIS', models.FloatField(default=0)),
                ('CST_COFINS', models.CharField(max_length=2)),
                ('VL_BC_COFINS', models.FloatField(default=0)),
                ('QUANT_BC_COFINS', models.FloatField(default=0)),
                ('ALIQ_COFINS', models.FloatField(default=0)),
                ('ALIQ_COFINS_PERCT', models.FloatField(default=0)),
                ('VL_COFINS', models.FloatField(default=0)),
                ('COD_CTA', models.FloatField(max_length=100)),
                ('NUM_DOC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Notas')),
            ],
        ),
    ]
